### ISSUE TITLE
does gorm support prefix/suffix mapping between struct name and table name?

### ISSUE THREAD

**Issue by bruceauyeung** [jinzhu/gorm#1034]
for example, i want to map struct `Employee` to table `prefix_employee`. 
[xorm has already support this](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/2.prefix.html).

**Comment by pjebs** [comment]
Create a method called TableName() on the struct to give a custom name.

**Comment by redhatlinux10** [comment]
thanks @pjebs for your reply. the way you provided means i have to define this `TableName()` for every struct, i think it will be better if gorm has builtin similar mechanism.

**Comment by nbgo** [comment]
General mapping rules definition/override would be nice for tables as well as columns.

**Comment by jinzhu** [comment]
Overwrite the `DefaultTableNameHandler` method

**Comment by ReSTARTR** [comment]
@jinzhu It doesn't work in using `db.AutoMigrate(Model{})` or `db.First(Model{})`.
Because DefaultNameHandler is called only from ModelStruct.
If a model implements tabler interface, DefaultNameHandler is never called.

So, I create pull request. Please take a look?
https://github.com/jinzhu/gorm/pull/1688
