### ISSUE TITLE
How Do I Set a Field To NULL?

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#1073]
I want to undelete some things, is there a proper way to do this?

**Comment by KlausVii** [comment]
I've found that if you use a nullable struct like [mysql.NullTime](https://godoc.org/github.com/go-sql-driver/mysql#NullTime) you can write null into it's field by setting the Time to a non-default value and setting Valid to false.

```
type Example struct {
	Id                     string
	SomeTime       mysql.NullTime
}
example := Example{ Id: "1", SomeTime: mysql.NullTime{ Time: Time.Now(), Valid: False}
db.Model(&example).Updates(&example)
// This produces UPDATE examples SET some_time = NULL WHERE Id = '1'
```
This works because gorm ignores fields with default values for update, but by setting the Time field, we force it to write Null.

**Comment by jinzhu** [comment]
or `Update("column", gorm.Expr("NULL"))` or use nil for pointer.

**Comment by thanhtungka91** [comment]
in the case, i have some some fields which i set type String in model, should i use  `Update("column", gorm.Expr("NULL"))` for multi times?
any option to update NULL?

**Comment by SantoshSah** [comment]
@jinzhu , any update for multiple columns and how can we insert multiple fields having NULL values for some fields?

**Comment by fsmiamoto** [comment]
@SantoshSah I have used with success a `map[string]interface{}` instead of a `struct` . Having `nil` as the value of the  desired `null` property
