### ISSUE TITLE
Warning message with unsupported drivers

### ISSUE THREAD

**Issue by vbatoufflet** [jinzhu/gorm#1085]
Hi,

In order to have regular expression support in the sqlite3 driver, I need to define an additional driver:

```
sql.Register("sqlite3_ext", &sqlite3.SQLiteDriver{
    ConnectHook: func(c *sqlite3.SQLiteConn) error {
        return c.RegisterFunc("regexp", regexp.MatchString, true)
    },
})
```

Doing that, I get this message dumped in the console:

```
`sqlite3_ext` is not officially supported, running under compatibility mode.
```

Do you think of a way to suppress this output or to register this override without triggerring it?

Thanks in advance for any help.

Regards,

**Comment by jinzhu** [comment]
```go
sqlDB := sql.Open("sqlite3_ext", "xxx")
gormDB := gorm.Open("sqlite", sqlDB)
```

**Comment by AntonioBusillo** [comment]
Sorry to open this issue again, I think there should be a way to suppress this log message, since it's very annoying when you do operations on multiple hosts. 

I have:  
> `odbc` is not officially supported, running under compatibility mode.

Using https://github.com/alexbrainman/odbc

And even if I try your method, I don't have any official dialects that I can use, since I use a propretary driver that supports only standard SQL.
