### ISSUE TITLE
build a web gui for gorm

### ISSUE THREAD

**Issue by joeblew99** [jinzhu/gorm#1089]
Since GORM supports a few DB's it woudl be very useful to have a web gui to inspect the DB's and the DB schema.

´Is there an existing one ?

**Comment by danhardman** [comment]
You're only likely to be using one DB at a time. What's the problem with using official DB Clients?

**Comment by pedromorgan** [comment]
OK So I like this idea as a concept...

The problem is that..
1) we got a GUI to remote db.. and phpmyadmin et all

2) Using gorm.. I think some of us are legacy, ie connecting to olde db with gorm..

3) gorm/control_panel/
It should be possible to create some "handlers" than can introspect the DB..
maybe this is a new plugiin gorm-www/

BTW i have a love and hate with db managers.. mysqlfront was the "don" in yoinder years.. Im 52 next week ;-))))))

But I would love a kinda "plugin" on a www app to intorspect db etc ;-)))

**Comment by pedromorgan** [comment]
https://github.com/freeflightsim/fg-navdb/blob/master/navdb/navaids.go#L50#

Retrospection of POSTGIS = postgres geospacial

**Comment by jinzhu** [comment]
GORM won't have this feature, if you want some similar things, refer: 

http://demo.getqor.com/admin
https://github.com/qor/admin
