### ISSUE TITLE
What's the difference between "hasOne" and "belongsTo"?

### ISSUE THREAD

**Issue by tsmaeder** [jinzhu/gorm#1131]
I don't understand and http://jinzhu.me/gorm/associations.html#belongs-to does not explain it.

**Comment by mdouchement** [comment]
Both are one-to-one relations but queries are impacted because IDs are not stored in the same way.

Ruby on Rails ORM documentation could help to understand the diffrence between `hasOne` and `belongsTo`:
- http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association
- http://guides.rubyonrails.org/association_basics.html#the-has-one-association


You may do cross references like this:
```
User has one Profile
Profile belongs to User
```

```
User has many Emails
Email belongs to User
```

**Comment by gkop** [comment]
The way I remember it is, the struct type with the "belongsTo" corresponds with the table with the foreign key column. In the gorm docs, `User` belongsTo `Profile`, so the users table has a column `profile_id`. With "hasOne" the _other_ table has the column with the foreign key; eg. in the docs, `User` hasOne `CreditCard`, so the credit_cards table has a column `user_id`.
