### ISSUE TITLE
Got "Duplicated entry '1' for key 'PRIMARY'" when specified the value of a `AUTO_INCREMENT` field

### ISSUE THREAD

**Issue by YamiOdymel** [jinzhu/gorm#1230]
## Problem

I want to manually set the `ID` field, but I've got an error message: `Duplicated entry '1' for key 'PRIMARY'` when I set it as `0`, **I must start it from `1` to solve the problem**, why?
## Struct

``` go
type Category struct {
    ID       uint
    Name     string        `gorm:"not null; index"`
    ParentID sql.NullInt64 `gorm:"index; default: null;"`
}
```
## Usage

``` go
data := []*Category{
        &Category{ID: 0, Name: "userSetting", ParentID: sql.NullInt64{Int64: 0, Valid: false}},
        &Category{ID: 1, Name: "general", ParentID: sql.NullInt64{Int64: 0, Valid: true}}}

    for _, row := range data {
        fmt.Println(row)
        s.DB.Create(row)
    }
```
## Output

``` bash
&{0 userSetting {0 false}}
&{1 general {0 true}}

(Error 1062: Duplicate entry '1' for key 'PRIMARY') 
```
## Result

![2016-10-20 3 15 59](https://cloud.githubusercontent.com/assets/7308718/19533728/8b1b600c-9673-11e6-83b8-f3a077382acd.png)

What I'm expecting:

![2016-10-20 3 16 49](https://cloud.githubusercontent.com/assets/7308718/19533753/aa8f66a4-9673-11e6-8e38-4f7114fcba6b.png)

**Comment by nkonk** [comment]
Before answering, It is well known that ID's should usually not start from 0, it is a bad practice.

ID 0 is special to MySQL AutoIncremented Fields.
Inserting 0 or null into a MySQL autoincremented column would reset the counter as described in below doc link.
So this will insert your item resetting the counter to 1. That's why you are getting 1 as ID.

_generate the next sequence number for the column by inserting either NULL or 0 into it._
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_value_on_zero

But if you still want to use 0 then you've to set a MySQL mode as

`SET [GLOBAL|SESSION] sql_mode='NO_AUTO_VALUE_ON_ZERO'`

This will allow you to use 0 as index but be careful, **you must maintain consistency and document this well**.

**Comment by YamiOdymel** [comment]
Thanks for the answer, it's very useful.
