### ISSUE TITLE
How to implement create or update?

### ISSUE THREAD

**Issue by Domoryonok** [jinzhu/gorm#1307]
Gorm has a FirstOrCreate method and a FirstOrInit but how to check afterwards if the record was actually created? I like to create a record if it does not exists and if it exists I want to update some fields. thx for answer

**Comment by TheChuckster** [comment]
I am also interested in this, but it looks like you will just have to use a transaction for now. I might be able to dig into submitting a PR for this when I have a spare weekend or two.

**Comment by jinzhu** [comment]
Maybe you can use the `Attrs`, `Assign` method with `FirstOrInit`, `FirstOrCreate`?

**Comment by spaceblock** [comment]
You "orm" not have this)

**Comment by TheChuckster** [comment]
@jinzhu Is that something I could potentially collapse into my own method in Gorm and submit a patch?

@spaceblock Do you have anything productive to add to this discussion?

**Comment by jinzhu** [comment]
Hi @TheChuckster 

> I like to create a record if it does not exists and if it exists I want to update some fields.

`FirstOrCreate` with `Assign` method will do the exactly thing.

![image](https://cloud.githubusercontent.com/assets/6843/26662100/5b881c3a-46b4-11e7-9650-b01da66420be.png)

refer:  http://jinzhu.me/gorm/crud.html#firstorcreate

**Comment by yasar-arafat** [comment]
Hi

**Comment by yasar-arafat** [comment]
Hi, I have multiple records. How can I do same for multiple records?

**Comment by vidhyashankarpaysafe** [comment]
> 
> 
> Hi @TheChuckster
> 
> > I like to create a record if it does not exists and if it exists I want to update some fields.
> 
> `FirstOrCreate` with `Assign` method will do the exactly thing.
> 
> ![image](https://cloud.githubusercontent.com/assets/6843/26662100/5b881c3a-46b4-11e7-9650-b01da66420be.png)
> 
> refer: http://jinzhu.me/gorm/crud.html#firstorcreate

How can i achieve the same for assigning using GORM expressions?  Something like below
db.Where(User{Name: "jinzhu"}).Assign("age", gorm.Expr("age+ ?", additionalAge).FirstOrCreate(&user)

**Comment by alexykot** [comment]
Hmm, this probably works, but it looks more as a workaround rather than actual solution. I.e. it's not atomic, uses two separate queries underneath and is not using native `ON CONFLICT...` clause. Also if you have many fields you'll have to create long chains of `Assign()` calls to enumerate all of them.

I'm achieving same thing the other way, via `gorm:insert_option`:
```
db.Model(dbModel).
	Set("gorm:insert_option",
	    fmt.Sprintf("ON CONFLICT (id) DO UPDATE SET field_1 = '%s', field2 = '%s' ", field1.String(), field2.String())).
	Create(dbModel)
```
The downside of this is that I have to craft a piece of SQL by hand, but it is atomic, Posgres-idiomatic and is much easier to understand imo. 

Ideally I would love to do something like `Set("ON CONFLICT (id) DO UPDATE SET field_1 = ?, field2 = ? ", field1, field2)`, I think that would be better option than any of current ones.
