### ISSUE TITLE
GORM doesn't support utf8mb4

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#1328]
Hello,

We are having problems with saving emoji even after we updated database, table, fields to make it support utf8mb4.

However when we insert a emoji into database with sql query in mysql terminal, it is inserted successfully, however if I use gorm to insert it, it gets failed, saying 
"Error 1366: Incorrect string value: '\xF0\x9F\x94\x86' for column 'weixin_name' at row 1 "

Could anyone explain how to make gorm support utf8mb4 correctly?

**Comment by pfzero** [comment]
Hi, it seems that `gorm` does some kind of stripping / conversion of the text. I have a similar problem when I try to save strings containing `(` and `)` to database via `gorm`. Those characters are encoded as `%28` and `%29` and when I query the data, the orm doesn't convert back to `(` and `)`.

I wanted to post this here because both issues seems to be related. Or maybe am I doing something wrong?

**Comment by jinzhu** [comment]
Hi @seaguest , @pfzero 

Could you please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to submit a complete runnable script, then I could look into it?

Thank you.

**Comment by canhlinh** [comment]
@seaguest  I'm using utf8mb4 in our production. It still works well.
