### ISSUE TITLE
Add Crate support

### ISSUE THREAD

**Issue by inge4pres** [jinzhu/gorm#1350]
It would be nice to have support for a new dialect for Crate to use gorm with [crate](http://crate.io). A sql-compatible driver is [herenow/go-crate](https://github.com/herenow/go-crate).

**Comment by jinzhu** [comment]
Thank you for your suggestion, will consider to support it when more people start using it.

Thank you.

**Comment by RichardLindhout** [comment]
Crate now works with the postgres interface.

The only change we had to make was
![screen shot 2018-03-02 at 10 47 12](https://user-images.githubusercontent.com/6492229/36893089-1899eb12-1e07-11e8-95c4-233f292fba18.png)


Also for relations we have added a before create which sets the unique UUID.

```
type Definition struct {
	ID          string `gorm:"primary_key"`
	Name        string `gorm:"not null"`
	Context     string
	Type        int32 `gorm:"not null"`
	Status      int32 `gorm:"not null"`
	Explanation string
	Solutions   []Solution
}

func (p *Definition) BeforeCreate(scope *gorm.Scope) (err error) {
	uuid, err := uuid.NewV4()
	if err != nil {
		return err
	}

	return scope.SetColumn("ID", uuid.String())
}


```

The only thing we do with hardcoded queries is creating the table in database because of the shards count.
