### ISSUE TITLE
SQL Syntax generated by Delete creates a lock on the entire table

### ISSUE THREAD

**Issue by dreemkiller** [jinzhu/gorm#1367]
I'm using MySQL.
When running with multiple goroutines, I was frequently getting a 'Deadlock found when trying to get lock; try restarting transaction'.

The internets tells me (http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans) that the problem is that the SQL generated for the unscoped delete operation ("DELETE FROM `table_name` WHERE id is 1234") creates a lock on the whole table. Since this is a very wide lock, any other transactions on the table will find a deadlock and generate this error.

To fix this, in my local branch I've changed the following code:
callback_delete.go, line 38-42:
			scope.Raw(fmt.Sprintf(
				"DELETE FROM %v%v%v",
				scope.QuotedTableName(),
				addExtraSpaceIfExist(scope.CombinedConditionSql()),
				addExtraSpaceIfExist(extraOption),
			)).Exec()
To the following:
			scope.Raw(fmt.Sprintf(
				"DELETE FROM %v WHERE id in(SELECT id FROM(SELECT id FROM %v%v%v) as x)",
				scope.QuotedTableName(),
				scope.QuotedTableName(),
				addExtraSpaceIfExist(scope.CombinedConditionSql()),
				addExtraSpaceIfExist(extraOption),
			)).Exec()

This works on my models. I hesitate to create a pull request because it may not be the general (or optimal) solution you guys would prefer.

An alternative (although perhaps slower) solution to this might be to have the operations on the tables repeat when they encounter a deadlock (which is what the error message suggests).

**Comment by dreemkiller** [comment]
I do still see a few deadlocks with this fix, so a complete fix would be to make changes similar to the above code, as well as repeating any MySQL commands that fail because of deadlock. As it is, I have to do the repeats in my code, which is not very clean, and is the kind of thing the ORM should do for me.

**Comment by dreemkiller** [comment]
Is there any update on this? I'm currently using my fork of the gorm repo, which is not ideal, but I can't really work with the main branch unless this is somehow fixed (doesn't need to be my solution, of course)

**Comment by jinzhu** [comment]
Hi @dreemkiller 

Could you create a test script that could reproduce this issue, I guess this might be caused by your application missing indexes caused table lock like https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans/2332866#2332866 said

**Comment by dreemkiller** [comment]
I now find myself unable to reproduce - my code base is at a very different place now. I'll close this out.

**Comment by dreemkiller** [comment]
I have no proposed fix (as I was unable to reproduce). If you look at my fork, you can see my change (it's only one change). I'd recommend making that change in your own fork, because my fork is quite out of date from @jinzhu's latest updates.
Also, if you are able to replicate it on a small example, I'm sure @jinzhu would appreciate it.

**Comment by sijad** [comment]
sorry for bumping this old issue, I just wanted to add my experience here for anyone who ran into similar issue. I got this error because of using goroutines.
my workers (goroutines) tried to inserts data to DB at the same time which results `Deadlock found when trying to get lock; try restarting transaction`.

I've found two solution for this issue:

1. lock threads using mutex:
```go
mutex.Lock()
DB.Create(&record)
mutex.Unlock()
```
2. use a separated thread to insert results via channel:
```go
func worker(wg *sync.WaitGroup, reusults chan<- Record) {	
	// ... do some work
	reusults <- Record{}
	wg.Done()
}

func main() {
	var wg sync.WaitGroup
	reusults := make(chan Record)

	for i := 0; i < 50; i++ {
		wg.Add(1)
		go worker(&wg, reusults)
	}

	go func() {
		for record := range reusults {
			wg.Add(1)
			db.Create(&record)
			wg.Done()
		}
	}()

	wg.Wait()
}
```

both of them works, I'm went with second solution as it does not block all threads.
I'm not an experienced go programmer this solutions might be wrong, please correct me if they're.
