### ISSUE TITLE
[Doc not specified] How to pass parameters to custom preloading functions?

### ISSUE THREAD

**Issue by beef9999** [jinzhu/gorm#1419]
`You could custom preloading SQL by passing in func(db *gorm.DB) *gorm.DB (same type as the one used for Scopes), for example:`

```
db.Preload("Orders", func(db *gorm.DB) *gorm.DB {
    return db.Order("orders.amount DESC")
}).Find(&users)
//// SELECT * FROM users;
//// SELECT * FROM orders WHERE user_id IN (1,2,3,4) order by orders.amount DESC;
```

**How to pass another parameter to the custom func?**

**Comment by hejrobin** [comment]
Just put your arguments outside the scope callback.

```go
leastAmount = 100
db.Preload("Orders", func(db *gorm.DB) *gorm.DB {
    return db.Order("orders.amount DESC").Having(fmt.Sprintf("orders.amount > %s", leastAmount))
}).Find(&users)
```

**Comment by beef9999** [comment]
It is not argument passing, I'm talking about a function call with an independent scope.

By the way, why even down vote me ...

**Comment by hejrobin** [comment]
I downvoted since this isn't directly related to GORM. You're passing a callback handler into another function, you obviously can't pass arguments to that callback since it's invoked and arguments are passed from the callee. No language I know of supports this behaviour.

You can still achive what you want by defining your arguments outside of the function scope.
