### ISSUE TITLE
[suggestion] Refer all usage questions to Stack Overflow

### ISSUE THREAD

**Issue by jbfm** [jinzhu/gorm#1422]
There are currently 160 open issues in Gorm, many are usage questions or other issues not really related to Gorm. I suggest adding a section to the contributor guide or the readme referring users to [Stack Overflow](http://stackoverflow.com/questions/tagged/go-gorm), and closing all issues that are usage questions. As it is now it's difficult to filter, follow, and fix issues when every other issue has nothing to do with the actual project.

Further I suggest adding a section to the contributor guide requiring issues to be posted in english, it's pretty difficult for us non-chinese speakers to help fix issues when they're impossible for us to read.

**Comment by beef9999** [comment]
This project is dead.

The author is vanished.

**Comment by zardak** [comment]
Project is far from dead.
Last pull request was accepted 1 day ago https://github.com/jinzhu/gorm/pull/1438.

@jinzhu , adding an issue template (https://github.com/blog/2111-issue-and-pull-request-templates) which says that usage questions should be posted on stackoverflow would greatly lower the count of unrelated issues.

**Comment by jinzhu** [comment]
@beef9999 just because people like you posting nothing valuable but only spam to waste other's time.

@jbfm thank you for your suggestion, just too busy recently, I will make a clean up soon.

@zardak thank you for your suggestion.

**Comment by beef9999** [comment]
`The fantastic ORM library for Golang, aims to be developer friendly`

I suggest you remove the last statement, because I don't see any clue that GORM is deserved to be called `developer friendly`.

No forum, no email threads, no official website, only some code examples rather than detailed documentation. And these questions in Github issues are seldom properly answered.

If you are too busy to answer these questions, please at least try to build a collaborative community so that other people can engage.

**Comment by jinzhu** [comment]
Have you even read GORM's document http://jinzhu.me/gorm/ or even its README, it says there is a online chat room https://gitter.im/jinzhu/gorm

Also I believe you haven't read our CONTRIBUTING guide, https://github.com/jinzhu/gorm/blob/79a91d75483d3ecb7a85d060749c98de38798129/CONTRIBUTING.md , or you won't submit issues like this https://github.com/jinzhu/gorm/issues/1421
