### ISSUE TITLE
v1.1 release?

### ISSUE THREAD

**Issue by paultag** [jinzhu/gorm#1543]
I see that there's a 1.0 tag, but it's pretty far off master.

Are you interested in maintaining regular releases? If so, would you mind tagging a new one soon?

Thanks for all your hard work!

**Comment by maugre** [comment]
+1

Just discovered an issue I was having (#952) was fixed but not in a tagged release yet. I can use master for now but would prefer not to in production.

**Comment by heyanlong** [comment]
+1

**Comment by mehdy** [comment]
+1
beside this I think it helps if we have a reliable versioning system and release time to time

**Comment by Towerthousand** [comment]
+1. I use golang/dep and it'll pull the latest tag by default, so it would be nice to keep doing them from time to time.

**Comment by mehdy** [comment]
@jinzhu btw, I could help if you want :)

**Comment by jinzhu** [comment]
Hello @mehdy 

Thank you, I would like to have regular releases after gorm v2.0, but don't have much time for this yet, hopefully, this could be done soon.

**Comment by mehdy** [comment]
@jinzhu :+1: . great, so if you needed a hand just notify me.

**Comment by jhartman86** [comment]
At this point the the docs are (somewhat significantly) different than whats in the 1.0 release tag. Since this is a pretty popular project, seems like properly versioned releases would make life a lot easier for a lot of people. I'm saying that selfishly, but seems like other people ^^ agree. At the very least, can tags be created for stable minor releases until v2 comes out? Thanks for the great work @jinzhu

**Comment by Depado** [comment]
Hi, I'd love to have some minor versions tags for gorm too. Since [dep](https://github.com/golang/dep) is quickly gaining interest and usage, it would be a good thing.

**Comment by jinzhu** [comment]
Will start this after v2 release.

Thank you for your report.
