### ISSUE TITLE
Can I Use Close()?

### ISSUE THREAD

**Issue by xxxxpenny** [jinzhu/gorm#1819]
I use gom to create a blog. I use Conn as a global variable. But I find mysql `Too many connections`
so I should use `Close()` to close connection after I use `Select()`? 
```
var Conn *grom.DB

func init() {
    var err error
    Conn, err = grom.Open("sqlite3", "xxx")
    if err != nil {
    }
}

func Select() {
   Conn.First(&product, 1)
}
```

**Comment by penguinpowernz** [comment]
You may want to program it differently.  If because you have it in the init function it may be called more than once.  You could print some logs there to see how many times it is being called. It could also be that since it doesn't look like you ever call close, simply stopping and starting the app may cause file handlers to stay open.  This could cause issues with sqlite databases.

My recommendation is to:

1. create the connection inside your main function
2. pass the connection down to the things that need it via function parameters
3. Do a `defer Conn.Close()` in your main function so that when the program exits, it will close the file handler

I am closing this since it seems like an issue with code design (plus you probably found a solution by now)
