### ISSUE TITLE
gorm calls Close() on a wrapped *sql.DB

### ISSUE THREAD

**Issue by antness** [jinzhu/gorm#1984]
gorm.Open allows us to wrap an existing sql.DB connection instead of opening a new one. But sometimes (in case when database is unavailable) gorm closes wrapped connection.

https://github.com/jinzhu/gorm/blob/0fd395ab37aefd2d50854f0556a4311dccc6f45a/main.go#L82
```golang
	// Send a ping to make sure the database connection is alive.
	if d, ok := dbSQL.(*sql.DB); ok {
		if err = d.Ping(); err != nil {
			d.Close()
		}
	}
```
In this case connection becomes unavailable to the external code which is supposed to manage it's lifecycle.

**Comment by ermik** [comment]
Nice catch. I suggest, since `.Open()` accepts `SQLCommon` as its argument, you can implement that interface yourself (truly wrap it) and override the `.Close()` method with a no-op.

Otherwise, this seems like intended behavior. The `.Close()` call is a circuit breaker, allowing the database failure to be "loud" — if it's unavailable — you WILL know. It may be inconvenient, but since you are implementing your own lifecycle logic — you'll be able to reconnect there during such failure. It actually makes it so much easier to detect if there is an error by polling connection for open state.
