### ISSUE TITLE
Gorm inserting Null for fields that have data using db.Create()

### ISSUE THREAD

**Issue by Nanixel** [jinzhu/gorm#2020]
Using the model:

type PlayerModel struct {
	id       int32
	team_id  int32
	name     string
	position string
	rating   int32
}

And this code:

func (service *playerservice) Draft(ctx context.Context, req *pb.DraftPlayerRequest, res *pb.Player) error {
	fmt.Println(req.TeamId)
	var model = PlayerModel{team_id: req.TeamId, name: req.Name, position: req.Position, rating: 89}
	fmt.Println(model.name)
	if err := service.db.Create(&model).Error; err != nil {
		fmt.Println(err)
		return err
	}
	var player = &pb.Player{Id: model.id, TeamId: req.TeamId, Name: req.Name, Position: req.Position, Rating: model.rating}

	res = player
	return nil
}

I am getting a record inserted into the database (postgres), but the data for the all fields (excluding the id) is Null.  I have added print statements to verify that data is there and it is.  There is no error being returned, just inserts an empty record.  I've had no luck finding anything regarding this.

**Comment by ermik** [comment]
The fields in `PlayerModel` struct should be public (capitalized) for ORM to be able to access them safely. You also need to annotate your struct to specify which field gorm will use for primary key since you are not using the default `gorm.Model` idiom as part of your struct.

If this doesn't help, try adding `.Debug()` to your query and seeing the SQL generated by GORM.
> http://gorm.io/docs/logger.html

**Comment by Nanixel** [comment]
Thanks for your help!

**Comment by Umarhayat3** [comment]
If anyone still faces this issue of null insertion into DB. Please have a look at this [answer](https://stackoverflow.com/questions/43587610/preventing-null-or-empty-string-values-in-the-db/59391882#59391882) on StackOverflow. thanks
