### ISSUE TITLE
Mysql time type cannot be obtained by time.time

### ISSUE THREAD

**Issue by gofromzero** [jinzhu/gorm#2274]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.11.4 windows/amd64

### Which database and its version are you using?
mysql 5.7.19-log

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

![image](https://user-images.githubusercontent.com/30290644/51652087-4e0eef80-1fc9-11e9-9de4-ee540e7d5801.png)

table:
![image](https://user-images.githubusercontent.com/30290644/51652016-14d67f80-1fc9-11e9-8b8e-5de3f7ad054b.png)

```
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"time"
)

var db *gorm.DB

type Good struct {
	ID   int `json:"id"`
	Name string
	Time time.Time
}

func (Good) TableName() string {
	return "good"
}

func main() {
	var err error
	db, err = gorm.Open("mysql", "root:123456@tcp(127.0.0.1:3306)/test?parseTime=true")

	if err != nil {
		panic(err)
	}
	db.LogMode(true)

	db.SingularTable(true)
	db.DB().SetMaxIdleConns(10)
	db.DB().SetMaxOpenConns(100)
	var g []*Good
	err = db.Model(&Good{}).Find(&g).Error
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(g)
}
```

**Comment by deslum** [comment]
Dialect "github.com/jinzhu/gorm/dialects/mysql" inherits "github.com/go-sql-driver/mysql"

Look Readme https://github.com/go-sql-driver/mysql
`parseTime=true changes the output type of DATE and DATETIME values to time.Time instead of []byte / string The date or datetime like 0000-00-00 00:00:00 is converted into zero value of time.Time.`

If you must use time type you'll need to do the parsing youself.

**Comment by gofromzero** [comment]
ok, thanks.
