### ISSUE TITLE
`TableName` mistake in doc?

### ISSUE THREAD

**Issue by fannheyward** [jinzhu/gorm#2448]
Code from https://gorm.io/docs/conventions.html

```go
type User struct {} // default table name is `users`

// Set User's table name to be `profiles`
func (User) TableName() string {
  return "profiles"
}
```

Why use `User` as method receiver? Shouldn't this be

```go
func (u User) TableName() string {
  return "profiles"
}
```

Thanks.

**Comment by emirb** [comment]
The method receiver doesn't need a variable `u` because it is not used in the method body at all. We can also assign the variable to blank identifier to ignore it:
```
func (_ User) TableName() string {
	return "profiles"
}
```

And it would still work the same way.

All these three variations can work, but the shortest and most clear is to omit the receiver name, like it is done in the example.
