### ISSUE TITLE
Has many relationship problems for Postgresql

### ISSUE THREAD

**Issue by jasondavindev** [jinzhu/gorm#2832]
**Go version**: 1.13.5
**Database version**: postgres 9.6

### Problem
I'm running exactly the same documentation example for has many relationships [here](https://gorm.io/docs/has_many.html#Foreign-Key), but it doesn't work.

I have the error message `invalid association []`

Codeblock:

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type User struct {
	gorm.Model
	CreditCards []CreditCard `gorm:"foreignkey:UserRefer"`
}

type CreditCard struct {
	gorm.Model
	Number    string
	UserRefer uint
}

func InitDB() *gorm.DB {
	db, err := gorm.Open("postgres", "url_connection_here")

	if err != nil {
		panic(err)
	}

	return db.Debug()
}

func main() {
	db := InitDB()

	db.AutoMigrate(&CreditCard{})
	db.AutoMigrate(&User{})

	user := &User{Model: gorm.Model{ID: 1}}
	db.Find(user)

	card := &CreditCard{UserRefer: user.ID}
	db.Model(user).Related(card)

	fmt.Println("User", user)
	fmt.Println("Card", card)
}
```

**Comment by sswanv** [comment]
In your example, the default foreign key for processing `Related` is` UserId && CreditCardId`, but you specified a custom foreign key in the tag, so that Released could not find the association。

The solution is to specify the relation field name in the `Related` method
```golang
db.Model(user).Related(card, "CreditCards")
```

Specific details can be found in the source code：[--->](https://github.com/jinzhu/gorm/blob/master/scope.go#L1070-L1116)

**Comment by jasondavindev** [comment]
Thanks for the reply, it worked.
Then the documentation must be updated to avoid problems like this.
