### ISSUE TITLE
Automigrate doesn't add foreign key?

### ISSUE THREAD

**Issue by sendyhalim** [jinzhu/gorm#349]
Hi there guys, I've been playing a bit with automigrate feature. By looking at the source, I realize that either create table or automigrate does not add foreign keys to related tables.
* Is this intended to be like this?
* For now I'm creating foreign keys manually (`db.Exec()`), is there more elegant approach?

Thanks!

**Comment by jinzhu** [comment]
Hi @sendyhalim 

Yes, this is intended to be like this.

This has been discussed many times, because different databases has different behaviour about it, so it is hard for gorm to auto generate them, maybe application level management should be enough for most cases. ;)

Although I am open to accept any pull requests about ths, not going to implement it myself. ;)

**Comment by sendyhalim** [comment]
@jinzhu Ohh I see, I will try code this feature and submit a pull request for this feature if I have spare time in weekend.

**Comment by jinzhu** [comment]
@sendyhalim it would be helpful ;)

**Comment by parkjinhong03** [comment]
Hello, guys! Minseok is so sexy man who leaves in Korean.
