### ISSUE TITLE
Compound primary index causes problem with Preload

### ISSUE THREAD

**Issue by mraxus** [jinzhu/gorm#519]
Using OSX and Postgres 9.4:

I have two structs that I have combined so that a struct can contain a number of language specific names:

```
type Prime struct {
	ID    string
	Names []PrimeName
}
type PrimeName struct {
	PrimeID string `gorm:"primary_key"`
	Lang    string `gorm:"primary_key"`
	Name    string
}
```

The PrimeName are just a helper table that is only intended to be used together with Prime.

I `i.DB.Create(&prime)` a new Prime looking like this:
```
prime := Prime{
	ID: "same",
	Names: []PrimeName{{
		Lang: "en-US",
		Name: "Same",
	}},
}
```

When I don't have the gorm:"primary_key" structs tag included in Name struct, the result, when `i.DB.Preload("Names").Where("id = ?", primeID).First(&prime)` the data (in JSON), is:
```
{
	"id": "same",
	"names": [{
		"language": "en-US",
		"name": "Same"
	}]
}
```
Just the same. However, when using the struct tags, the result becomes:
```
{
	"id": "same",
	"names": []
}
```

When looking into the queries being name, the create performs two inserts when the struct tags are not included. However, when they are, only the Prime table gets an SQL INSERT. The PrimeName performs an UPDATE instead.

I have a working gist to test this with, one struct name with the gorm struct tag and one without to show the difference:
https://gist.github.com/mraxus/9e59b6c5aa34c5c74f89

**Comment by jinzhu** [comment]
Gorm think `PrimeName` as an existing record as it already has an ID, so will perform the `Update`.

You should create it by using `db.Create(&primeName)` by yourself if it's primary key already has value.

**Comment by lpetre** [comment]
I don't like this change very much. I ran some gorm tests here:
https://gist.github.com/lpetre/4cf1b07568de42232e8b

My findings are that this isn't specific to compound keys, it is anywhere we use a `gorm:"primary_key"` tag. In my opinion it is safer to use that tag than not to use it, but it messes with our create statements.

What about passing an array of values to be created to the creator helper. So we pass an array with the WagerState and all the WagerBets to the helper instead of just the WagerState.
