### ISSUE TITLE
SAP HANA support

### ISSUE THREAD

**Issue by zasran** [jinzhu/gorm#615]
Any thoughts on SAP HANA support? I have no experience with gorm but it looks like we only need an implementation of Dialect interface using https://github.com/SAP/go-hdb?

**Comment by pedromorgan** [comment]
SAP and HANA is a proprierty ss tem and u can use the force to read the source..

U can of course use golang and its cool..

So this issue is closed for that reason..

 eg

- when will gorm support oracle
  - When Ellison is dead
  - will Bill gaes be there - probably

So your question is misterious..

So u want a free copy of oracle HANA + Support

So please I understand.. But now its in your court... eg e tennis or swinign court of a ..

I guess @jinzhu would would probably accept that.. say I as a "helper".. but probably not..

**Comment by jinzhu** [comment]
Doesn't seem much people using that, will add its support when more people start using it.
