### ISSUE TITLE
Postgres bool default problem

### ISSUE THREAD

**Issue by litmisty** [jinzhu/gorm#689]
I have a model has bool field with default value.
The problem is I can't insert a row with bool value.

```
func TestCreateWithBoolDefaultValue(t *testing.T) {
	type Data struct {
		ID            int    `gorm:"column:id;primary_key" json:"id"`
		Name          string `sql:"type:varchar(100);not null;unique" json:"name"`
		DeleteAllowed bool   `sql:"not null;DEFAULT:true" json:"delete_allowed"`
	}

	DB.AutoMigrate(&Data{})

	data := Data{
		Name:          "test",
		DeleteAllowed: false,
	}

	DB.Create(&data)

	if data.DeleteAllowed {
		t.Error("Test failed")
	}
}
```

It yields this SQL
```
INSERT INTO "data" ("name") VALUES ('test forum 1') RETURNING "data"."id"
```

I think it should be 
```
INSERT INTO "data" ("name", "delete_allowed") VALUES ('test forum 1', false) RETURNING "data"."id"
```

I want know this is a bug or the policy.

**Comment by DSchalla** [comment]
Its not related to the boolean values, I am having a PSQL Table with the structure:
```golang
type User struct {
	ID           uint `gorm:"primary_key"`
	Name         string
	DisplayName  string
	EMail        string
	Partner      bool
	Logo         string
	AccessToken  string
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    time.Time
}
```
And migrations & create work correctly, including boolean value. Might help to track the bug down.

**Comment by litmisty** [comment]
I couldn't resolve this problem, so just get rid of default bool value from structure and insert it explicitly.

**Comment by galeone** [comment]
The problem here is that the boolean field has a default value, and the default value is false.

For the boolean values, Go consider `false` the zero of the type. Thus, when we check if the field is empty, we got true. This is due to the fact that `reflect.Zero(TypeOf(false))` is the same of false.

Thereforse, I suggest you to

1. or to remove the  `DEFAULT` value in your field tag. `sql:"not null"
2. or to change the table structure (and the related field tag), making `default:true`

**Comment by jinzhu** [comment]
Added more documents about this. refer https://github.com/jinzhu/gorm/tree/v1.0_dev#default-values

Feedback welcome in #794

**Comment by LiamDotPro** [comment]
@jinzhu link broken and ranks highly in search results, http://gorm.io/docs/create.html#Default-Values
