### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by andrevalgrande** [jinzhu/gorm#699]
Hi,

Is there a proper way to implement nested transactions in gorm? Say with local commits, cascade rollbacks, etc.

Best regards,

André

**Comment by jinzhu** [comment]
Hi @andrevalgrande 

Gorm doesn't support nested transactions, maybe you need to run raw sql for this.

You could run raw sql with `Raw` `Execute`

**Comment by invasionofsmallcubes** [comment]
Sorry if I reopen the issue, but could you be more clear on how to achieve this with `Raw`?

I can't understand how to make it work. First of all, `Raw` by itself doesn't work.
You always need to call another method to execute.
I tried something like:

```
	var result []models.Brand
	tx = models.Db.Raw("BEGIN TRANSACTION; SELECT * FROM brands;").Scan(&result)
```

but if I pass `tx` around then I get weird queries like:

```WHERE "countries"."deleted_at" IS NULL AND ((BEGIN TRANSACTION; SELECT * FROM brands;)```

because gorm puts the raw content in the`AND` clause of the next query.

If I run execute transaction without passing this reference, the transaction if it starts, it's not used by the next gorm call.
