### ISSUE TITLE
Introspection + www Interface

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#810]
Is it possible to "introspect" a database via..

### interogate gorm
Having method such as `gorm.Tables()` and `gorm.Table("foo").Columns()` to get data out of gorm on the way it sees things. This would be useful

## Interrogate actual db schema
aqquiring data from upstream of what the actual column, table etc is..

The cunning plan is to create a "gorm.www" and a http server, much like phpmyadmin.. 

Even though this is in the future.. I like the idea very much on having some  "plugin" that works on the back of gorm.. cos that works and dont wanna reinvent a wheel... Hey I'm a laxy programmer...

**Comment by jinzhu** [comment]
For `gorm.Table("foo").Columns()`, we will support this in the future, in order to make a better auto migration.

But for `gorm.www`, not going to add those kind of feature into gorm, although I do write a similar software could be used like this, refer http://getqor.com

And there are lots of other tools could be used to manage database like `phpmyadmin`, I don't really like to add this feature into gorm, as it will make gorm became complicated ;(
