### ISSUE TITLE
Tagging versions of the library

### ISSUE THREAD

**Issue by yassirh** [jinzhu/gorm#902]
From what i have got from the [changelog](http://jinzhu.me/gorm/changelog.html) is that version 1.0 was released. however there is no way to distinguish the right commit. so Is there a chance we get tagged versions of the library? to avoid breaking the builds of applications that use gorm? it is hard to test and maintain an application that uses the master version of a library. Thanks.

**Comment by dvdplm** [comment]
+1

**Comment by jinzhu** [comment]
Hi, I am going add this in the following days, if no one report any serious bug

**Comment by onlyjob** [comment]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by pedromorgan** [comment]
Noted.. 

Idea of golang is we build from source.. embeedded iin your applilaction..

**Comment by onlyjob** [comment]
Unfortunately "idea of golang" threw away 20 years of best practice in software engineering...

Security support in distributions like Debian (where many apps may depend on the same library) is possible only with reusable libraries.
Large applications like Docker and Kubernetes have long dependency chains maybe around 200 libraries. It is hard to track changes in all those dependencies and re-build application every time when dependency is patched. In reality bundled libraries are not properly tracked and their test suites are not even run on rebuild of application. Those problems are effectively addressed by using source packages on build time (instead of messy source trees with vendored dependencies).

**Comment by yassirh** [comment]
@pedromorgan What is requested here is that we can have tagged version of the library so that we can be able to write code against a stable version of this library.

If we keep building against the latest version of the code we would have to retest our entire application every new commit on this library. i don't know about you but i find that very tedious.

**Comment by kennwhite** [comment]
I think what you want is this: https://github.com/jinzhu/gorm/releases/tag/v1.0 (the 5174cc5 commit).
And though `go get` can't handle versions, you can use the (excellent) gvt vendoring tool:
`gvt fetch -revision 0cf369dcff417ed51c8e439d8047f1b7503d87ce github.com/jinzhu/gorm`
In fact, you may want to consider vendoring *all* 3rd party packages and libraries, lest your builds may suddenly stop working some day because of a bc-breaking master commit somewhere.

**Comment by onlyjob** [comment]
Thanks! :)
